# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            jim
tagline:
description:
url:              http://jimiray.github.io
baseurl:          /

author:
  name:           'Jim Ray'
  url:            https://twitter.com/jimiray

paginate:         10

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/jimiray/jimiray.github.io

description: 
google_analytics: 
show_downloads: true
theme: jekyll-theme-slate