# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            jimiray
tagline:
description:
url:              http://jimiray.github.io
baseurl:          /

author:
  name:           'Jim Ray'
  url:            https://twitter.com/jimiray

paginate:         10

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/jimiray/jimiray.github.io
